// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // CLI/migration commands (migrate, db push, studio) connect directly, bypassing
  // the connection pooler — required for schema changes. The running app uses a
  // separate pooled connection, wired up in src/lib/prisma.ts via a driver adapter.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
